#!/usr/bin/env python3
"""
Pack SCUMM picker thumbnails (PNG → 4-bit indexed RGB565) into a C
source file compiled into the SCUMM slot binary.

Usage:
    pack_scumm_thumbs.py <thumbs_dir> <out_c>

Mirrors the lobby's tools/pack_icons.py format but at 64x64 instead of
48x48 — the SCUMM picker's hero card has a 64x64 thumbnail slot.

The thumbs directory should contain one PNG per supported game,
named after the descriptor's `subdir` field in
engine/src/game_table.cpp:

    mi1.png    Monkey Island 1 (v4 floppy)
    mi2.png    Monkey Island 2 (v5)
    indy3.png  Indiana Jones 3 (EGA, v3)
    indy4.png  Indiana Jones 4 — Fate of Atlantis (v5)

Each PNG is resized to 64x64 (NEAREST), quantised to a 16-colour
adaptive palette, and emitted as:

    static const uint16_t scumm_thumb_<subdir>_palette[16];
    static const uint8_t  scumm_thumb_<subdir>_pixels[64 * 64 / 2];

Plus a `scumm_thumbs[]` table the picker indexes by game subdir name.
Two pixels per byte: even pixel high nibble, odd low.

Memory cost: 32 bytes palette + 2048 bytes pixels = 2080 bytes per
thumbnail. Four games = ~8.3 KB total, baked into the slot binary's
.rodata.
"""

import os
import sys

from PIL import Image


THUMB_W = 64
THUMB_H = 64
NCOL    = 16

# Must match the descriptor subdirs in engine/src/game_table.cpp.
GAMES = [
    "mi1",
    "mi2",
    "indy3",
    "indy4",
]


def rgb_to_rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def load_as_indexed(path: str):
    img = Image.open(path).convert("RGB")
    if img.size != (THUMB_W, THUMB_H):
        img = img.resize((THUMB_W, THUMB_H), Image.NEAREST)
    qimg = img.quantize(colors=NCOL, method=Image.MEDIANCUT, dither=Image.NONE)

    pal_raw = qimg.getpalette()
    needed = NCOL * 3
    if len(pal_raw) < needed:
        pal_raw = list(pal_raw) + [0] * (needed - len(pal_raw))
    palette = [
        rgb_to_rgb565(pal_raw[i * 3], pal_raw[i * 3 + 1], pal_raw[i * 3 + 2])
        for i in range(NCOL)
    ]

    pixels = list(qimg.getdata())
    pixels = [min(p, NCOL - 1) for p in pixels]
    return palette, pixels


def emit(thumbs_dir: str, out_c: str) -> None:
    out = []
    out.append("/* Auto-generated by pack_scumm_thumbs.py — do not edit. */\n")
    out.append('#include "scumm_thumbs.h"\n\n')

    table_entries = []
    missing = []

    for subdir in GAMES:
        path = os.path.join(thumbs_dir, subdir + ".png")
        if not os.path.exists(path):
            missing.append(path)
            # Emit zero arrays so the table is well-formed.
            out.append(
                f"static const uint16_t scumm_thumb_{subdir}_palette[{NCOL}] = {{ 0 }};\n"
            )
            out.append(
                f"static const uint8_t  scumm_thumb_{subdir}_pixels"
                f"[{THUMB_W * THUMB_H // 2}] = {{ 0 }};\n\n"
            )
            table_entries.append((subdir, False))
            continue

        palette, pixels = load_as_indexed(path)

        out.append(f"static const uint16_t scumm_thumb_{subdir}_palette[{NCOL}] = {{\n")
        for i in range(0, NCOL, 8):
            row = ", ".join(f"0x{c:04x}" for c in palette[i:i + 8])
            out.append(f"    {row},\n")
        out.append("};\n\n")

        out.append(
            f"static const uint8_t scumm_thumb_{subdir}_pixels"
            f"[{THUMB_W * THUMB_H // 2}] = {{\n"
        )
        for y in range(THUMB_H):
            row_bytes = []
            for x in range(0, THUMB_W, 2):
                hi = pixels[y * THUMB_W + x]
                lo = pixels[y * THUMB_W + x + 1]
                row_bytes.append((hi << 4) | lo)
            row = ", ".join(f"0x{b:02x}" for b in row_bytes)
            out.append(f"    {row},\n")
        out.append("};\n\n")

        table_entries.append((subdir, True))

    out.append("const scumm_thumb_t scumm_thumbs[] = {\n")
    for subdir, present in table_entries:
        out.append(f'    {{ "{subdir}", '
                   f'scumm_thumb_{subdir}_palette, '
                   f'scumm_thumb_{subdir}_pixels }},\n')
    out.append("};\n\n")
    out.append(f"const int scumm_thumbs_count = "
               f"sizeof(scumm_thumbs) / sizeof(scumm_thumbs[0]);\n")

    with open(out_c, "w") as f:
        f.writelines(out)

    if missing:
        print(f"pack_scumm_thumbs: WARNING — missing PNGs (emitted zero-fill):",
              file=sys.stderr)
        for p in missing:
            print(f"  {p}", file=sys.stderr)


def main():
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        sys.exit(2)
    emit(sys.argv[1], sys.argv[2])


if __name__ == "__main__":
    main()
