#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Extract MI1 charset 1 (901.LFL) into engine/include/mi_font.h.
#
# SCUMM v4 charset on-disk layout (after the 4-byte file-size header
# and the 17-byte resource-manager skip — net 21 bytes):
#   off 0   bpp                  (1 byte)
#   off 1   max font height      (1 byte)
#   off 2   num_chars            (uint16 LE — typically 256)
#   off 4   offset table         (num_chars * uint32 LE)
#   off ..  per-glyph records: { width, height, sint8 oX, sint8 oY, bitmap }
#                               bitmap is contiguous bitstream, MSB-first,
#                               width*height*bpp bits, padded to a byte.
import struct, sys
SKIP = 21
def main(in_path, out_path):
    with open(in_path, "rb") as f: data = f.read()
    p = SKIP
    bpp, fh = data[p], data[p+1]
    nc = struct.unpack_from("<H", data, p+2)[0]
    assert bpp == 1, f"expected 1bpp, got {bpp}"
    FIRST, LAST = 0x20, 0x7E
    out = []                       # (w, h, oX, oY, bitmap_bytes)
    blob = bytearray()
    meta = []
    for c in range(FIRST, LAST+1):
        offs_in = struct.unpack_from("<I", data, p + 4 + c*4)[0]
        if offs_in == 0:
            meta.append((0, 0, 0, 0, 0xFFFF))
            continue
        ofs = p + offs_in
        w, h = data[ofs], data[ofs+1]
        oX = struct.unpack_from("<b", data, ofs+2)[0]
        oY = struct.unpack_from("<b", data, ofs+3)[0]
        nbytes = (w * h * bpp + 7) // 8
        bm = data[ofs+4 : ofs+4+nbytes]
        meta.append((w, h, oX, oY, len(blob)))
        blob.extend(bm)
    with open(out_path, "w") as f:
        f.write("// SPDX-License-Identifier: GPL-3.0-or-later\n")
        f.write("// AUTOGENERATED by tools/extract_mi_font.py.  Do not edit by hand.\n")
        f.write("// Source: 901.LFL (charset 1) — MI1 small/system font.\n")
        f.write("//\n")
        f.write("// Each glyph is a contiguous 1bpp bitstream, MSB-first, width*height\n")
        f.write("// bits, byte-padded.  Glyph metrics live in kGlyphs; bitmap data in\n")
        f.write("// kBitmaps.  Skipped chars (no glyph) carry bitmap_offset = 0xFFFF.\n")
        f.write(f"// Range: 0x{FIRST:02X}..0x{LAST:02X} ({LAST-FIRST+1} glyphs).\n")
        f.write(f"// Max h={fh}px, bpp={bpp}.  Blob {len(blob)} B + meta {len(meta)*6} B.\n")
        f.write("#pragma once\n#include <stdint.h>\nnamespace tsb {\nnamespace mi_font {\n\n")
        f.write(f"constexpr int kFirstChar = 0x{FIRST:02X};\n")
        f.write(f"constexpr int kLastChar  = 0x{LAST:02X};\n")
        f.write(f"constexpr int kMaxHeight = {fh};\n")
        f.write(f"constexpr int kCharCount = {LAST-FIRST+1};\n\n")
        f.write("struct Glyph { uint8_t width, height; int8_t offsX, offsY; uint16_t bitmap_offset; };\n\n")
        f.write("static const Glyph kGlyphs[kCharCount] = {\n")
        for i, (w, h, oX, oY, off) in enumerate(meta):
            ch = i + FIRST
            shown = chr(ch) if 32 < ch < 127 else " "
            f.write(f"    {{ {w:2d}, {h:2d}, {oX:3d}, {oY:3d}, 0x{off:04X} }},  // 0x{ch:02X} '{shown}'\n")
        f.write("};\n\n")
        f.write(f"static const uint8_t kBitmaps[{len(blob)}] = {{\n    ")
        for i, b in enumerate(blob):
            f.write(f"0x{b:02X},")
            f.write("\n    " if (i+1) % 12 == 0 else " ")
        f.write("\n};\n\n}}  // namespace tsb::mi_font\n")

if __name__ == "__main__":
    in_path  = sys.argv[1] if len(sys.argv) > 1 else "data/mi1_vga/901.LFL"
    out_path = sys.argv[2] if len(sys.argv) > 2 else "engine/include/mi_font.h"
    main(in_path, out_path)
